services:
    es01:
        container_name: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
        ports: 
            - "9200:9200"
        environment:
            - "node.name=es01"
            - "discovery.seed_hosts=es02"
            - "cluster.name=es-cluster"
            - "cluster.initial_master_nodes=es01,es02"
            - "http.cors.enabled=true"
            - "http.cors.allow-origin='http://localhost:3000'"
            - "xpack.security.enabled=false"
            - "network.host=0.0.0.0" # Required for colima
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Need to tell elastic search the heap size
        networks:
            - elastic-network
    es02:
        container_name: es02
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
        ports: 
            - "9201:9200"
        environment:
            - "node.name=es02"
            - "discovery.seed_hosts=es01"
            - "cluster.name=es-cluster"
            - "cluster.initial_master_nodes=es01,es02"
            - "http.cors.enabled=true"
            - "http.cors.allow-origin='http://localhost:3000'"
            - "xpack.security.enabled=false"
            - "network.host=0.0.0.0" # Required for colima
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Need to tell elastic search the heap size
        networks:
            - elastic-network
    dataloader:
        container_name: dataloader
        image: python:3.9.21
        volumes:
            - "./cv-index.py:/app/cv-index.py"
            - "./requirements.txt:/app/requirements.txt"
            - "../data/final_cv-valid-dev.csv:/data/final_cv-valid-dev.csv" # Your data path should be at ../data/final_cv-valid-dev.csv
        environment:
            - "ES_HOSTS=es01,es02" # service cannot use comma since it is used as a separator here
        working_dir: "/app"
        command: "bash -c 'pip install -r requirements.txt && python cv-index.py'"
        networks:
            - elastic-network
        depends_on:
            - "es01"
            - "es02"
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "8080:8080"  # Expose NGINX to port 8080
        volumes:
            # - ./nginx.conf:/etc/nginx/conf.d/default.conf  # NGINX configuration
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - elastic-network
        depends_on:
            - es01
            - es02
            - dataloader
networks:
  elastic-network:
    external: true